import type { Metadata } from 'next';
import { Noto_Serif_TC } from 'next/font/google';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const notoSerifTC = Noto_Serif_TC({
  subsets: ['latin'],
  variable: '--noto-serif-tc',
  weight: ['400', '500', '600', '700'],
  display: 'swap',
  preload: false,
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={notoSerifTC.variable}>
        <AppRouterCacheProvider>{children}</AppRouterCacheProvider>
      </body>
    </html>
  );
}
